-- Cal.diy-shaped Supabase bootstrap for the vNext port.
-- This is the first backend scaffold only; access policies come in a follow-up pass.

begin;

create extension if not exists pgcrypto;

create type public.scheduling_type as enum ('roundRobin', 'collective', 'managed');
create type public.period_type as enum ('unlimited', 'rolling', 'rolling_window', 'range');
create type public.membership_role as enum ('member', 'admin', 'owner');
create type public.user_permission_role as enum ('USER', 'ADMIN');
create type public.identity_provider as enum ('CAL', 'GOOGLE', 'SAML', 'AZUREAD');
create type public.booking_status as enum ('cancelled', 'accepted', 'rejected', 'pending', 'awaiting_host');
create type public.creation_source as enum ('api_v1', 'api_v2', 'webapp');
create type public.booking_audit_type as enum ('record_created', 'record_updated', 'record_deleted');
create type public.booking_audit_action as enum (
  'created',
  'cancelled',
  'accepted',
  'rejected',
  'pending',
  'awaiting_host',
  'rescheduled',
  'attendee_added',
  'attendee_removed',
  'reassignment',
  'location_changed',
  'no_show_updated',
  'reschedule_requested',
  'seat_booked',
  'seat_rescheduled'
);
create type public.booking_audit_source as enum ('api_v1', 'api_v2', 'webapp', 'webhook', 'system', 'magic_link', 'unknown');
create type public.audit_actor_type as enum ('user', 'guest', 'attendee', 'system', 'app');

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  uuid uuid not null unique default gen_random_uuid(),
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  username text,
  name text,
  email text not null,
  email_verified timestamptz,
  bio text,
  avatar_url text,
  time_zone text not null default 'Europe/London',
  week_start text not null default 'Sunday',
  buffer_time integer not null default 0,
  hide_branding boolean not null default false,
  theme text,
  app_theme text,
  created_at timestamptz not null default now(),
  trial_ends_at timestamptz,
  last_active_at timestamptz,
  completed_onboarding boolean not null default false,
  locale text,
  time_format integer,
  two_factor_enabled boolean not null default false,
  identity_provider public.identity_provider not null default 'CAL',
  identity_provider_id text,
  allow_dynamic_booking boolean not null default true,
  allow_seo_indexing boolean not null default true,
  receive_monthly_digest_email boolean not null default true,
  requires_booker_email_verification boolean not null default false,
  metadata jsonb,
  verified boolean default false,
  role public.user_permission_role not null default 'USER',
  locked boolean not null default false,
  brand_color text,
  dark_brand_color text,
  organization_id bigint,
  unique (email),
  unique (email, username),
  unique (username, organization_id)
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text,
  logo_url text,
  cal_video_logo text,
  app_logo text,
  app_icon_logo text,
  bio text,
  hide_branding boolean not null default false,
  hide_team_profile_link boolean not null default false,
  is_private boolean not null default false,
  hide_book_a_team_member boolean not null default false,
  created_at timestamptz not null default now(),
  metadata jsonb,
  theme text,
  brand_color text,
  dark_brand_color text,
  banner_url text,
  parent_id bigint references public.teams(id) on delete cascade,
  time_format integer,
  time_zone text not null default 'Europe/London',
  week_start text not null default 'Sunday',
  is_organization boolean not null default false,
  pending_payment boolean not null default false,
  is_platform boolean not null default false,
  auto_opt_in_features boolean not null default false,
  unique (slug, parent_id)
);

alter table public.users
  add constraint users_organization_id_fkey
  foreign key (organization_id) references public.teams(id) on delete set null;

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  uid text not null,
  user_id bigint not null references public.users(id) on delete cascade,
  organization_id bigint not null references public.teams(id) on delete cascade,
  username text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, organization_id),
  unique (username, organization_id)
);

create table if not exists public.memberships (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  accepted boolean not null default false,
  role public.membership_role not null,
  custom_role_id text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (user_id, team_id)
);

create table if not exists public.credentials (
  id bigint generated by default as identity primary key,
  type text not null,
  key jsonb not null,
  encrypted_key text,
  user_id bigint references public.users(id) on delete cascade,
  team_id bigint references public.teams(id) on delete cascade,
  app_id text,
  subscription_id text,
  payment_status text,
  billing_cycle_start integer,
  invalid boolean default false,
  delegation_credential_id text
);

create table if not exists public.event_types (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null,
  description text,
  interface_language text,
  position integer not null default 0,
  locations jsonb,
  length integer not null,
  offset_start integer not null default 0,
  hidden boolean not null default false,
  user_id bigint references public.users(id) on delete cascade,
  profile_id bigint references public.profiles(id),
  team_id bigint references public.teams(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, slug)
);

create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  time_zone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.availability (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  event_type_id bigint references public.event_types(id) on delete cascade,
  days integer[] not null,
  start_time time not null,
  end_time time not null,
  date date,
  schedule_id bigint references public.schedules(id) on delete cascade
);

create table if not exists public.selected_calendars (
  id uuid primary key default gen_random_uuid(),
  user_id bigint not null references public.users(id) on delete cascade,
  integration text not null,
  external_id text not null,
  credential_id bigint references public.credentials(id) on delete cascade,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  google_channel_id text,
  google_channel_kind text,
  google_channel_resource_id text,
  google_channel_resource_uri text,
  google_channel_expiration text,
  channel_id text,
  channel_kind text,
  channel_resource_id text,
  channel_resource_uri text,
  channel_expiration timestamptz,
  sync_subscribed_at timestamptz,
  sync_subscribed_error_at timestamptz,
  sync_subscribed_error_count integer not null default 0,
  sync_token text,
  synced_at timestamptz,
  sync_error_at timestamptz,
  sync_error_count integer default 0,
  delegation_credential_id text
);

create table if not exists public.destination_calendars (
  id bigint generated by default as identity primary key,
  integration text not null,
  external_id text not null,
  primary_email text,
  user_id bigint references public.users(id) on delete cascade,
  event_type_id bigint references public.event_types(id) on delete cascade,
  credential_id bigint references public.credentials(id) on delete cascade,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  delegation_credential_id text,
  custom_calendar_reminder integer
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  uid text not null unique,
  idempotency_key text unique,
  user_id bigint references public.users(id) on delete cascade,
  user_primary_email text,
  event_type_id bigint references public.event_types(id),
  title text not null,
  description text,
  custom_inputs jsonb,
  responses jsonb,
  start_time timestamptz not null,
  end_time timestamptz not null,
  location text,
  created_at timestamptz not null default now(),
  updated_at timestamptz default now(),
  status public.booking_status not null default 'accepted',
  paid boolean not null default false,
  destination_calendar_id bigint references public.destination_calendars(id),
  cancellation_reason text,
  rejection_reason text,
  reassign_reason text,
  reassign_by_id bigint references public.users(id),
  dynamic_event_slug_ref text,
  dynamic_group_slug_ref text,
  rescheduled boolean,
  from_reschedule text,
  recurring_event_id text,
  sms_reminder_number text,
  scheduled_jobs text[],
  metadata jsonb,
  is_recorded boolean not null default false,
  i_cal_uid text not null default '',
  i_cal_sequence integer not null default 0,
  one_time_password text unique default gen_random_uuid()::text,
  cancelled_by text,
  rescheduled_by text,
  creation_source public.creation_source,
  no_show_host boolean default false,
  rating integer,
  rating_feedback text
);

create table if not exists public.attendees (
  id bigint generated by default as identity primary key,
  email text not null,
  name text not null,
  time_zone text not null,
  phone_number text,
  locale text default 'en',
  booking_id bigint references public.bookings(id) on delete cascade,
  no_show boolean default false
);

create table if not exists public.booking_references (
  id bigint generated by default as identity primary key,
  type text not null,
  uid text not null,
  meeting_id text,
  third_party_recurring_event_id text,
  meeting_password text,
  meeting_url text,
  booking_id bigint references public.bookings(id) on delete cascade,
  external_calendar_id text,
  deleted boolean,
  credential_id bigint references public.credentials(id) on delete set null,
  delegation_credential_id text
);

create table if not exists public.audit_actors (
  id uuid primary key default gen_random_uuid(),
  type public.audit_actor_type not null,
  user_uuid uuid,
  attendee_id bigint,
  credential_id bigint,
  email text,
  phone text,
  name text,
  created_at timestamptz not null default now(),
  unique (user_uuid),
  unique (attendee_id),
  unique (credential_id),
  unique (email),
  unique (phone)
);

create table if not exists public.booking_audits (
  id uuid primary key default gen_random_uuid(),
  booking_uid text not null,
  actor_id uuid not null references public.audit_actors(id) on delete restrict,
  type public.booking_audit_type not null,
  action public.booking_audit_action not null,
  timestamp timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  source public.booking_audit_source not null,
  operation_id text not null,
  data jsonb,
  context jsonb
);

create table if not exists public.host_groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  event_type_id bigint references public.event_types(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hosts (
  user_id bigint not null references public.users(id) on delete cascade,
  event_type_id bigint not null references public.event_types(id) on delete cascade,
  is_fixed boolean not null default false,
  priority integer,
  weight integer,
  weight_adjustment integer,
  schedule_id bigint references public.schedules(id),
  group_id uuid references public.host_groups(id),
  member_id bigint references public.memberships(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, event_type_id)
);

create table if not exists public.host_locations (
  id uuid primary key default gen_random_uuid(),
  user_id bigint not null,
  event_type_id bigint not null,
  type text not null,
  credential_id bigint references public.credentials(id) on delete set null,
  link text,
  address text,
  phone_number text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, event_type_id),
  foreign key (user_id, event_type_id) references public.hosts(user_id, event_type_id) on delete cascade
);

create table if not exists public.video_call_guests (
  id uuid primary key default gen_random_uuid(),
  booking_uid text not null,
  email text not null,
  name text not null,
  joined_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (booking_uid, email)
);

create table if not exists public.webhooks (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  team_id bigint references public.teams(id) on delete cascade,
  event_type_id bigint references public.event_types(id) on delete cascade,
  active boolean not null default true,
  url text not null,
  secret text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.teams enable row level security;
alter table public.profiles enable row level security;
alter table public.memberships enable row level security;
alter table public.credentials enable row level security;
alter table public.event_types enable row level security;
alter table public.schedules enable row level security;
alter table public.availability enable row level security;
alter table public.selected_calendars enable row level security;
alter table public.destination_calendars enable row level security;
alter table public.bookings enable row level security;
alter table public.attendees enable row level security;
alter table public.booking_references enable row level security;
alter table public.audit_actors enable row level security;
alter table public.booking_audits enable row level security;
alter table public.host_groups enable row level security;
alter table public.hosts enable row level security;
alter table public.host_locations enable row level security;
alter table public.video_call_guests enable row level security;
alter table public.webhooks enable row level security;

commit;
